"""Updating ticket table

Revision ID: edb3d2b62b97
Revises: 4159e3cd87ee
Create Date: 2026-02-11 22:35:01.227432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb3d2b62b97'
down_revision: Union[str, Sequence[str], None] = '4159e3cd87ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'deleted_at')
    # ### end Alembic commands ###
